spin_manifest_version = 2

[application]
name = "logger"
version = "0.0.1"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "root"

[component.logger]
source = "target/wasm32-wasip1/release/logger.wasm"
allowed_outbound_hosts = []

[component.logger.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
